import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import styles from "./app.module.scss";
import { ToastContainer } from "react-toastify";
import { headers } from "next/headers";
import { auth } from "@/src/lib/auth";
import Link from "next/link";
import { Button } from "react-bootstrap";
import "bootstrap/dist/css/bootstrap.min.css";
import { SessionProvider } from "./providers/SessionProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth.api.getSession({
    headers: await headers(),
  });

  // console.log("session22222222222", session?.user);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${styles.window} antialiased`}
      >
        <SessionProvider
          session={session ? JSON.parse(JSON.stringify(session)) : null}
        >
          <div className={styles.workZone}>
            {children}
            <ToastContainer />
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}
